# Generated by Django 4.2.7 on 2025-09-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Semester'), (2, '2 Semester'), (3, '3 Semester'), (4, '4 Semester'), (5, '5 Semester'), (6, '6 Semester'), (7, '7 Semester'), (8, '8 Semester')], default=1),
        ),
    ]
