# Generated by Django 4.2.7 on 2025-09-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='field',
            field=models.CharField(choices=[('computer', 'Computer Engineering'), ('software', 'Software Engineering'), ('it', 'Information Technology')], default='computer', max_length=20),
        ),
    ]
