# Generated by Django 4.2.7 on 2025-08-31 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(choices=[('TU', 'Tribhuvan University'), ('PU', 'Purbanchal University'), ('KU', 'Kathmandu University'), ('PoU', 'Pokhara University'), ('MU', 'Mid-Western University'), ('FU', 'Far-Western University'), ('LU', 'Lumbini University')], max_length=3)),
                ('location', models.CharField(max_length=200)),
                ('established_year', models.IntegerField()),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='college_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('IOE', 'Institute of Engineering'), ('KU', 'Kathmandu University'), ('PU', 'Purbanchal University'), ('PoU', 'Pokhara University')], max_length=3)),
                ('exam_date', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('total_questions', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('passing_score', models.IntegerField()),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_exams', to='colleges.college')),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('BE', 'Bachelor of Engineering'), ('BArch', 'Bachelor of Architecture'), ('BTech', 'Bachelor of Technology')], max_length=5)),
                ('duration_years', models.IntegerField(default=4)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('fee_structure', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='colleges.college')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
