# Generated by Django 4.2.7 on 2025-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='type',
            field=models.CharField(choices=[('entrance', 'Entrance'), ('notes', 'Notes')], default='notes', max_length=20),
        ),
    ]
